import Phaser from 'phaser';
import { CAT } from '../config';

export type ObstacleKind = 'wreck' | 'rock' | 'ramp';

/** Per-kind tuning. */
interface ObstacleStats {
  /** Procedural texture key generated by PreloadScene. */
  textureKey: string;
  /** Unique Matter body label for collision routing in GameScene. */
  label: string;
  /** Cash awarded when smashed (wrecks only). */
  cashValue: number;
  /** Static bodies never move; dynamic bodies can be shoved. */
  isStatic: boolean;
  /** Approx half sprite height (px) used to rest the base on groundY. */
  halfH: number;
  density?: number;
  friction?: number;
}

const STATS: Record<ObstacleKind, ObstacleStats> = {
  wreck: {
    textureKey: 'tex-wreck',
    label: 'obstacle-wreck',
    cashValue: 15,
    isStatic: false,
    halfH: 28,
    // Heavy enough to feel solid, light enough that a fast car bulldozes it.
    density: 0.0085,
    friction: 0.5,
  },
  rock: {
    textureKey: 'tex-rock',
    label: 'obstacle-rock',
    cashValue: 0,
    isStatic: true,
    halfH: 24,
  },
  ramp: {
    textureKey: 'tex-ramp',
    label: 'obstacle-ramp',
    cashValue: 0,
    isStatic: true,
    halfH: 20,
  },
};

/** Launch tilt for the ramp, in degrees (negative = nose-up to fling the car). */
const RAMP_ANGLE_DEG = -18;

/**
 * A world obstacle:
 *  - wreck: dynamic rusted car, smashable when hit at speed (awards cash).
 *  - rock:  static immovable boulder — a hard stop.
 *  - ramp:  static angled launcher that flings the car into a stunt arc.
 */
export class Obstacle {
  readonly sprite: Phaser.Physics.Matter.Sprite;
  readonly kind: ObstacleKind;
  readonly cashValue: number;
  smashed = false;

  constructor(scene: Phaser.Scene, x: number, groundY: number, kind: ObstacleKind) {
    this.kind = kind;
    const stats = STATS[kind];
    this.cashValue = stats.cashValue;

    // Rest the sprite base on the ground line.
    const spawnY = groundY - stats.halfH;

    if (kind === 'ramp') {
      this.sprite = Obstacle.createRamp(scene, x, spawnY, stats);
    } else {
      this.sprite = scene.matter.add.sprite(x, spawnY, stats.textureKey, undefined, {
        label: stats.label,
        isStatic: stats.isStatic,
        density: stats.density,
        friction: stats.friction,
        frictionAir: 0.01,
        collisionFilter: { category: CAT.terrain },
      });
    }

    this.sprite.setDepth(5);
    this.sprite.setData('obstacle', this);
  }

  /**
   * Build the ramp body. Preferred shape is a right-triangle wedge so the car
   * climbs a real incline; we fall back to an angled rectangle if the texture
   * frame can't be measured (shouldn't happen with the generated atlas).
   */
  private static createRamp(
    scene: Phaser.Scene,
    x: number,
    spawnY: number,
    stats: ObstacleStats,
  ): Phaser.Physics.Matter.Sprite {
    const frame = scene.textures.getFrame(stats.textureKey);
    const w = frame ? frame.width : 96;
    const h = frame ? frame.height : 48;

    const commonOpts = {
      label: stats.label,
      isStatic: true,
      friction: 0.6,
      collisionFilter: { category: CAT.terrain },
    } as const;

    // Right-triangle wedge: flat base, vertical back edge, hypotenuse facing the
    // incoming car (low on the left, high on the right) so contact ramps it up.
    const verts = `0 ${h} ${w} ${h} ${w} 0`;
    const sprite = scene.matter.add.sprite(x, spawnY, stats.textureKey, undefined, {
      ...commonOpts,
      shape: { type: 'fromVerts', verts, flagInternal: true },
    });

    // If fromVerts silently failed (degenerate body), use an angled rectangle.
    if (!sprite.body) {
      return scene.matter.add.sprite(x, spawnY, stats.textureKey, undefined, {
        ...commonOpts,
        angle: Phaser.Math.DegToRad(RAMP_ANGLE_DEG),
      });
    }

    return sprite;
  }

  /**
   * Smash a wreck: weaken its collision so it stops jolting the car, then fling
   * and tumble it before fading out. No-ops for non-wrecks or repeat calls.
   */
  smash(scene: Phaser.Scene, dir: number): void {
    if (this.kind !== 'wreck' || this.smashed) return;
    this.smashed = true;

    const body = this.sprite.body as MatterJS.BodyType;

    // Make it nearly weightless so follow-up contacts barely register.
    scene.matter.body.setDensity(body, 0.0005);
    this.sprite.setTint(0x555555);

    const sign = dir >= 0 ? 1 : -1;
    scene.matter.body.setVelocity(body, { x: sign * 5, y: -3 });
    this.sprite.setAngularVelocity(sign * 0.25);

    scene.tweens.add({
      targets: this.sprite,
      alpha: 0,
      duration: 600,
      delay: 300,
      ease: 'Quad.in',
      onComplete: () => this.sprite.destroy(),
    });
  }
}
