/**
 * Parallax background for Earn to Die — Evac Run.
 *
 * Builds, back-to-front, a self-contained scenic backdrop that sits entirely
 * behind gameplay (all depths in the -100..-50 range):
 *
 *   depth  scrollFactor  layer
 *   ─────  ────────────  ─────────────────────────────────────────────
 *   -100   0             sky gradient (skyTop → skyBottom)
 *    -97   0             horizon haze band (skyBottom glow near the floor)
 *    -95   0.05          celestial body (sun / moon / blood moon) + glow
 *    -90   0.20          far hill silhouette  (theme.hillFar)
 *    -80   0.45          near hill silhouette (theme.hillNear)
 *    -50   0             fog overlay (white @ theme.fog)   — only if fog > 0
 *
 * Parallax drift is produced purely by Phaser's per-object `scrollFactor`, so
 * no per-frame `update()` is required. Every created object is retained and
 * torn down together via `destroy()`.
 *
 * All generated textures use the `tex-parallax-` prefix plus a per-instance
 * counter, so multiple Parallax instances (e.g. across stage restarts) never
 * collide in the global texture cache.
 */

import Phaser from 'phaser';
import type { Theme } from '../data/levels';

/** Texture-key prefix; keeps generated textures clear of game art. */
const KEY_PREFIX = 'tex-parallax-';

/** Monotonic per-instance id, ensuring unique texture keys. */
let instanceCounter = 0;

/** Linearly blend two 0xRRGGBB colours; `t` in [0,1] (0 = a, 1 = b). */
function mixColor(a: number, b: number, t: number): number {
  const c = Phaser.Display.Color.Interpolate.ColorWithColor(
    Phaser.Display.Color.ValueToColor(a),
    Phaser.Display.Color.ValueToColor(b),
    100,
    Math.round(Phaser.Math.Clamp(t, 0, 1) * 100),
  );
  return Phaser.Display.Color.GetColor(c.r, c.g, c.b);
}

export class Parallax {
  /** Every object owned by this instance; all destroyed together. */
  private readonly objects: Phaser.GameObjects.GameObject[] = [];

  /** Texture keys generated by this instance (cleaned up on destroy). */
  private readonly textureKeys: string[] = [];

  private readonly id: number;

  /**
   * Build the full parallax stack.
   *
   * @param scene  Phaser scene the layers are added to.
   * @param theme  Stage palette driving every colour.
   * @param viewW  Viewport width  in pixels.
   * @param viewH  Viewport height in pixels.
   */
  constructor(
    private readonly scene: Phaser.Scene,
    theme: Theme,
    viewW: number,
    viewH: number,
  ) {
    this.id = instanceCounter++;
    this.buildSky(theme, viewW, viewH);
    this.buildHorizonHaze(theme, viewW, viewH);
    this.buildCelestial(theme, viewW, viewH);
    this.buildHills(theme, viewW, viewH);
    this.buildFog(theme, viewW, viewH);
  }

  // -------------------------------------------------------------------------
  // Layer builders
  // -------------------------------------------------------------------------

  /** Full-viewport vertical sky gradient (skyTop at top → skyBottom at base). */
  private buildSky(theme: Theme, viewW: number, viewH: number): void {
    const g = this.scene.add.graphics();
    g.fillGradientStyle(
      theme.skyTop, // top-left
      theme.skyTop, // top-right
      theme.skyBottom, // bottom-left
      theme.skyBottom, // bottom-right
      1,
    );
    g.fillRect(0, 0, viewW, viewH);
    g.setDepth(-100);
    g.setScrollFactor(0);
    this.objects.push(g);
  }

  /**
   * A soft horizon glow: a brightened band of the sky's own horizon colour,
   * fading upward from the hill line. Adds atmospheric depth without clashing
   * with any palette.
   */
  private buildHorizonHaze(theme: Theme, viewW: number, viewH: number): void {
    // Brighten the horizon colour slightly toward white for the glow tint.
    const glow = mixColor(theme.skyBottom, 0xffffff, 0.18);
    const bandTop = viewH * 0.42;
    const bandH = viewH * 0.28;

    const g = this.scene.add.graphics();
    // Transparent at the top → opaque-ish glow at the bottom of the band.
    g.fillGradientStyle(glow, glow, glow, glow, 0, 0, 0.35, 0.35);
    g.fillRect(0, bandTop, viewW, bandH);
    g.setDepth(-97);
    g.setScrollFactor(0);
    this.objects.push(g);
  }

  /** Sun, moon, or blood moon — baked to a texture, placed in the upper sky. */
  private buildCelestial(theme: Theme, viewW: number, viewH: number): void {
    const type = theme.celestial;

    // Blood moon hangs larger and more central; sun/moon sit upper-right.
    const cx = type === 'bloodmoon' ? viewW * 0.52 : viewW * 0.76;
    const cy = type === 'bloodmoon' ? viewH * 0.26 : viewH * 0.2;
    const radius = type === 'bloodmoon' ? 56 : 40;

    const key = `${KEY_PREFIX}celestial-${this.id}`;
    const pad = 28; // room for the glow halo
    const size = (radius + pad) * 2;
    const mid = size / 2;

    const g = this.scene.make.graphics({ x: 0, y: 0, add: false });

    if (type === 'sun') {
      // Warm layered corona.
      g.fillStyle(0xfff2a0, 0.12);
      g.fillCircle(mid, mid, radius + pad);
      g.fillStyle(0xffeb88, 0.22);
      g.fillCircle(mid, mid, radius + 16);
      g.fillStyle(0xffe170, 0.4);
      g.fillCircle(mid, mid, radius + 7);
      // Bright disc with a hot core.
      g.fillStyle(0xffd94a, 1);
      g.fillCircle(mid, mid, radius);
      g.fillStyle(0xfff3b0, 0.55);
      g.fillCircle(mid, mid, radius * 0.6);
    } else if (type === 'moon') {
      // Cool, faint halo.
      g.fillStyle(0xcfe6ff, 0.1);
      g.fillCircle(mid, mid, radius + pad);
      g.fillStyle(0xdcefff, 0.2);
      g.fillCircle(mid, mid, radius + 12);
      // Pale disc.
      g.fillStyle(0xe7f1fb, 1);
      g.fillCircle(mid, mid, radius);
      // A couple of subtle maria for character.
      g.fillStyle(0xc6d4e4, 0.5);
      g.fillCircle(mid - radius * 0.3, mid - radius * 0.25, radius * 0.22);
      g.fillCircle(mid + radius * 0.28, mid + radius * 0.18, radius * 0.16);
    } else {
      // Blood moon — baleful crimson with a smouldering core and dim halo.
      g.fillStyle(0x5a0000, 0.12);
      g.fillCircle(mid, mid, radius + pad);
      g.fillStyle(0x7e0202, 0.24);
      g.fillCircle(mid, mid, radius + 14);
      g.fillStyle(0xb01408, 1);
      g.fillCircle(mid, mid, radius);
      g.fillStyle(0xdd3a14, 0.65);
      g.fillCircle(mid, mid, radius * 0.62);
      g.fillStyle(0x7a0606, 0.45);
      g.fillCircle(mid + radius * 0.25, mid - radius * 0.2, radius * 0.3);
    }

    g.generateTexture(key, size, size);
    g.destroy();
    this.textureKeys.push(key);

    const img = this.scene.add.image(cx, cy, key);
    img.setDepth(-95);
    img.setScrollFactor(0.05);
    this.objects.push(img);
  }

  /**
   * Two rolling-hill silhouette layers. Each silhouette is generated from a
   * layered-sine profile drawn into a Graphics object (vertically gradient-
   * filled for subtle depth) and baked to a tileable texture, then added as a
   * full-width TileSprite anchored at its base.
   */
  private buildHills(theme: Theme, viewW: number, viewH: number): void {
    // ── Far hills: wide, gentle undulations, slightly lightened toward sky ──
    const farKey = `${KEY_PREFIX}hills-far-${this.id}`;
    const farTexW = 512;
    const farTexH = 170;
    this.makeHillTexture(farKey, farTexW, farTexH, {
      topColor: mixColor(theme.hillFar, theme.skyBottom, 0.25),
      baseColor: theme.hillFar,
      baselineY: farTexH * 0.52,
      waves: [
        { freq: (2 * Math.PI) / farTexW, amp: farTexH * 0.34, phase: 0 },
        { freq: (2 * Math.PI) / (farTexW * 0.55), amp: farTexH * 0.14, phase: 1.1 },
      ],
    });

    const farTile = this.scene.add.tileSprite(
      viewW / 2,
      viewH * 0.6,
      viewW,
      farTexH,
      farKey,
    );
    farTile.setOrigin(0.5, 1);
    farTile.setDepth(-90);
    farTile.setScrollFactor(0.2);
    this.objects.push(farTile);

    // ── Near hills: choppier, deeper, anchored lower over the terrain ──
    const nearKey = `${KEY_PREFIX}hills-near-${this.id}`;
    const nearTexW = 512;
    const nearTexH = 210;
    this.makeHillTexture(nearKey, nearTexW, nearTexH, {
      topColor: mixColor(theme.hillNear, theme.hillFar, 0.35),
      baseColor: theme.hillNear,
      baselineY: nearTexH * 0.48,
      waves: [
        { freq: (2 * Math.PI) / (nearTexW * 0.7), amp: nearTexH * 0.36, phase: 0.4 },
        { freq: (2 * Math.PI) / (nearTexW * 0.38), amp: nearTexH * 0.17, phase: 2.0 },
        { freq: (2 * Math.PI) / (nearTexW * 0.2), amp: nearTexH * 0.07, phase: 0.9 },
      ],
    });

    const nearTile = this.scene.add.tileSprite(
      viewW / 2,
      viewH * 0.66,
      viewW,
      nearTexH,
      nearKey,
    );
    nearTile.setOrigin(0.5, 1);
    nearTile.setDepth(-80);
    nearTile.setScrollFactor(0.45);
    this.objects.push(nearTile);
  }

  /**
   * Bake a seamlessly horizontally-tileable hill silhouette.
   *
   * The profile is the sum of sine waves whose frequencies are exact integer
   * multiples of the texture width's fundamental, guaranteeing a seam-free
   * horizontal loop. The body is filled with a vertical gradient
   * (`topColor` → `baseColor`) for a touch of aerial depth.
   */
  private makeHillTexture(
    key: string,
    texW: number,
    texH: number,
    opts: {
      topColor: number;
      baseColor: number;
      baselineY: number;
      waves: Array<{ freq: number; amp: number; phase: number }>;
    },
  ): void {
    const { topColor, baseColor, baselineY, waves } = opts;

    const heightAt = (x: number): number => {
      let h = baselineY;
      for (const w of waves) {
        h += Math.sin(x * w.freq + w.phase) * w.amp;
      }
      return h;
    };

    const g = this.scene.make.graphics({ x: 0, y: 0, add: false });
    const steps = texW;

    // Vertical gradient fill via thin horizontal slices clipped to the curve.
    // We draw the silhouette as one gradient-filled polygon by filling the
    // whole band then masking is overkill — instead approximate the gradient
    // with a small number of stacked bands, each clipped to the hill profile.
    const bands = 24;
    for (let b = 0; b < bands; b++) {
      const t0 = b / bands;
      const color = mixColor(topColor, baseColor, t0);
      g.fillStyle(color, 1);
      g.beginPath();
      g.moveTo(0, texH);
      for (let i = 0; i <= steps; i++) {
        const x = (i / steps) * texW;
        // Each band starts a little lower than the previous, revealing the
        // band beneath; the topmost band traces the true silhouette.
        const yTop = heightAt(x) + (texH - heightAt(x)) * t0;
        g.lineTo(x, yTop);
      }
      g.lineTo(texW, texH);
      g.closePath();
      g.fillPath();
    }

    g.generateTexture(key, texW, texH);
    g.destroy();
    this.textureKeys.push(key);
  }

  /** Translucent white fog sheet over the whole viewport (if theme.fog > 0). */
  private buildFog(theme: Theme, viewW: number, viewH: number): void {
    if (theme.fog <= 0) {
      return;
    }
    const g = this.scene.add.graphics();
    g.fillStyle(0xffffff, theme.fog);
    g.fillRect(0, 0, viewW, viewH);
    g.setDepth(-50);
    g.setScrollFactor(0);
    this.objects.push(g);
  }

  // -------------------------------------------------------------------------
  // Public API
  // -------------------------------------------------------------------------

  /** Destroy every object and generated texture owned by this instance. */
  destroy(): void {
    for (const obj of this.objects) {
      obj.destroy();
    }
    this.objects.length = 0;

    for (const key of this.textureKeys) {
      if (this.scene.textures.exists(key)) {
        this.scene.textures.remove(key);
      }
    }
    this.textureKeys.length = 0;
  }
}
