import Phaser from 'phaser';
import { CAT } from '../config';

export type ZombieType = 'walker' | 'brute' | 'crawler';

/** Per-type tuning table. */
interface ZombieStats {
  /** Procedural texture key generated by PreloadScene. */
  textureKey: string;
  /** Y offset (px) so the body's base rests on the terrain (~half sprite height). */
  heightOffset: number;
  /** Sprite/body scale. */
  scale: number;
  /** Matter density — drives how hard a contact shoves the car. */
  density: number;
  /** Hits to kill. */
  health: number;
  /** Cash awarded on death. */
  cashValue: number;
  /** Multiplier on splatter fling velocity — heavy brutes barely move. */
  flingScale: number;
}

const STATS: Record<ZombieType, ZombieStats> = {
  walker: {
    textureKey: 'tex-zombie',
    heightOffset: 24,
    scale: 1.0,
    density: 0.0006,
    health: 1,
    cashValue: 6,
    flingScale: 1.0,
  },
  brute: {
    textureKey: 'tex-zombie-brute',
    heightOffset: 36,
    scale: 1.5,
    density: 0.0024,
    health: 3,
    cashValue: 20,
    flingScale: 0.4,
  },
  crawler: {
    textureKey: 'tex-zombie-crawler',
    heightOffset: 10,
    scale: 0.7,
    density: 0.0004,
    health: 1,
    cashValue: 10,
    flingScale: 1.25,
  },
};

/**
 * A horde unit that ragdolls when smacked by the car.
 * Three flavours: walker (baseline), brute (tanky, barely budges),
 * crawler (small, fast, worth more than a walker).
 */
export class Zombie {
  readonly sprite: Phaser.Physics.Matter.Sprite;
  readonly type: ZombieType;
  readonly cashValue: number;
  dead = false;

  private health: number;
  private readonly flingScale: number;

  constructor(scene: Phaser.Scene, x: number, y: number, type: ZombieType = 'walker') {
    this.type = type;
    const stats = STATS[type];
    this.health = stats.health;
    this.cashValue = stats.cashValue;
    this.flingScale = stats.flingScale;

    this.sprite = scene.matter.add.sprite(x, y - stats.heightOffset, stats.textureKey, undefined, {
      label: `zombie-${type}`,
      density: stats.density,
      friction: 0.4,
      frictionAir: 0.02,
      collisionFilter: { category: CAT.zombie, mask: CAT.terrain | CAT.car },
    });

    if (stats.scale !== 1.0) {
      this.sprite.setScale(stats.scale);
    }

    // Upright until killed; lock so the car's torque can't tip it pre-death.
    this.sprite.setFixedRotation();
    this.sprite.setDepth(6);

    const body = this.sprite.body as MatterJS.BodyType;
    // Back-references so GameScene collision pairs can resolve the wrapper.
    body.gameObject = this.sprite;
    this.sprite.setData('zombie', this);
  }

  /**
   * Apply damage. Returns true exactly once — on the hit that drops health to 0.
   * No-ops (returns false) if already dead, preventing double-kills/double-payouts.
   */
  hit(dmg: number): boolean {
    if (this.dead) return false;
    this.health -= dmg;
    return this.health <= 0;
  }

  /**
   * Ragdoll the corpse: stop colliding with the car, tint blood-dark,
   * fling (biased by travel direction), spin, then fade out and destroy.
   * Call once after hit() reports a kill. No-ops if already splattered.
   */
  splatter(scene: Phaser.Scene, dir: number): void {
    if (this.dead) return;
    this.dead = true;

    const body = this.sprite.body as MatterJS.BodyType;

    // Drop out of the car's collision set so the corpse stops adding drag.
    body.collisionFilter.mask = CAT.terrain;

    this.sprite.setTint(0x8b0000);

    // Allow the dead body to tumble freely now that it's not a standing zombie.
    this.sprite.setFixedRotation();
    this.sprite.setStatic(false);

    const sign = dir >= 0 ? 1 : -1;
    const vx = sign * (5 + Math.random() * 2) * this.flingScale;
    const vy = -(4 + Math.random() * 3) * this.flingScale;
    scene.matter.body.setVelocity(body, { x: vx, y: vy });
    this.sprite.setAngularVelocity(sign * 0.4 * this.flingScale);

    scene.tweens.add({
      targets: this.sprite,
      alpha: 0,
      duration: 700,
      delay: 250,
      ease: 'Quad.in',
      onComplete: () => this.sprite.destroy(),
    });
  }
}
